export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_PROVIDERS_START = "FETCH_PROVIDERS_START";
export const FETCH_PROVIDERS_SUCCESS = "FETCH_PROVIDERS_SUCCESS";
export const FETCH_PROVIDERS_FAILURE = "FETCH_PROVIDERS_FAILURE";

export const REFILL_BALANCE_START = "REFILL_BALANCE_START";
export const REFILL_BALANCE_SUCCESS = "REFILL_BALANCE_SUCCESS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT = "LOGOUT";
